package db

import "strings"

// Dialect identifies the SQL backend a database handle talks to. The store's
// statements are written once in SQLite form; the PostgreSQL adapter rewrites
// the few constructs that differ.
type Dialect int

const (
	// SQLite is the embedded default backend.
	SQLite Dialect = iota
	// Postgres is an external PostgreSQL server.
	Postgres
)

// DetectDialect returns the backend implied by a DSN. PostgreSQL connections
// use the postgres:// or postgresql:// URL scheme; every other value is a
// SQLite file path.
func DetectDialect(dsn string) Dialect {
	trimmed := strings.ToLower(strings.TrimSpace(dsn))
	if strings.HasPrefix(trimmed, "postgres://") || strings.HasPrefix(trimmed, "postgresql://") {
		return Postgres
	}
	return SQLite
}

// ResolvePath maps a legacy .json store path onto the SQLite file the store
// actually uses; other paths and DSNs are returned unchanged.
func ResolvePath(path string) string {
	if strings.HasSuffix(path, ".json") {
		return strings.TrimSuffix(path, ".json") + ".db"
	}
	return path
}

// IsPostgresDSN reports whether dsn addresses a PostgreSQL server instead of a
// SQLite file.
func IsPostgresDSN(dsn string) bool {
	return DetectDialect(dsn) == Postgres
}

// String implements fmt.Stringer for logs and configuration output.
func (d Dialect) String() string {
	if d == Postgres {
		return "postgres"
	}
	return "sqlite"
}

// translateSchema rewrites one migration script from the SQLite form used in
// this package to the given dialect.
func translateSchema(stmts string, dialect Dialect) string {
	if dialect != Postgres {
		return stmts
	}
	// SQLite's INTEGER is a 64-bit value and INTEGER PRIMARY KEY
	// AUTOINCREMENT is a rowid alias: both map onto PostgreSQL's 64-bit
	// integer and an identity column.
	pg := strings.ReplaceAll(stmts, "INTEGER PRIMARY KEY AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
	return strings.ReplaceAll(pg, "INTEGER", "BIGINT")
}

// splitStatements splits a migration script on top-level semicolons so each
// statement can be executed on its own. PostgreSQL refuses multiple commands
// in one prepared statement, which database/sql uses inside a transaction.
func splitStatements(script string) []string {
	var (
		stmts []string
		start int
	)
	for i := 0; i < len(script); {
		switch script[i] {
		case '\'', '"', '`':
			i = skipQuoted(script, i)
		case '-':
			if i+1 < len(script) && script[i+1] == '-' {
				i = skipLineComment(script, i)
				continue
			}
			i++
		case '/':
			if i+1 < len(script) && script[i+1] == '*' {
				i = skipBlockComment(script, i)
				continue
			}
			i++
		case ';':
			if stmt := strings.TrimSpace(script[start:i]); stmt != "" {
				stmts = append(stmts, stmt)
			}
			i++
			start = i
		default:
			i++
		}
	}
	if stmt := strings.TrimSpace(script[start:]); stmt != "" {
		stmts = append(stmts, stmt)
	}
	return stmts
}

// RewritePlaceholders converts the ? placeholders used throughout the store
// into the $N form PostgreSQL expects. Quoted strings, quoted identifiers and
// comments are copied verbatim, so a literal question mark never turns into a
// parameter.
func RewritePlaceholders(query string) string {
	if !strings.ContainsRune(query, '?') {
		return query
	}
	var (
		out strings.Builder
		n   int
	)
	out.Grow(len(query) + 8)
	for i := 0; i < len(query); {
		switch query[i] {
		case '\'', '"', '`':
			end := skipQuoted(query, i)
			out.WriteString(query[i:end])
			i = end
		case '-':
			if i+1 < len(query) && query[i+1] == '-' {
				end := skipLineComment(query, i)
				out.WriteString(query[i:end])
				i = end
				continue
			}
			out.WriteByte(query[i])
			i++
		case '/':
			if i+1 < len(query) && query[i+1] == '*' {
				end := skipBlockComment(query, i)
				out.WriteString(query[i:end])
				i = end
				continue
			}
			out.WriteByte(query[i])
			i++
		case '?':
			n++
			out.WriteByte('$')
			out.WriteString(itoa(n))
			i++
		default:
			out.WriteByte(query[i])
			i++
		}
	}
	return out.String()
}

// skipQuoted returns the index just past the quoted run that starts at i. The
// quote character is repeated to embed itself (” or ""), which is the only
// escape both SQLite and PostgreSQL share.
func skipQuoted(s string, i int) int {
	quote := s[i]
	for i++; i < len(s); i++ {
		if s[i] != quote {
			continue
		}
		if i+1 < len(s) && s[i+1] == quote {
			i++
			continue
		}
		return i + 1
	}
	return len(s)
}

// skipLineComment returns the index just past the -- comment that starts at i.
func skipLineComment(s string, i int) int {
	for ; i < len(s); i++ {
		if s[i] == '\n' {
			return i + 1
		}
	}
	return len(s)
}

// skipBlockComment returns the index just past the /* */ comment at i.
func skipBlockComment(s string, i int) int {
	for i += 2; i+1 < len(s); i++ {
		if s[i] == '*' && s[i+1] == '/' {
			return i + 2
		}
	}
	return len(s)
}

// itoa appends a small positive integer without pulling in strconv.
func itoa(n int) string {
	if n < 10 {
		return string(rune('0' + n))
	}
	var digits [20]byte
	i := len(digits)
	for n > 0 {
		i--
		digits[i] = byte('0' + n%10)
		n /= 10
	}
	return string(digits[i:])
}
