import type { GlobalThemeOverrides } from 'naive-ui'

export const warmThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#a34b2a',
    primaryColorHover: '#82391f',
    primaryColorPressed: '#6a2d19',
    primaryColorSuppl: '#a34b2a',
    bodyColor: '#f5f1e8',
    cardColor: '#fffdf8',
    modalColor: '#fffdf8',
    popoverColor: '#fffdf8',
    tableColor: '#fffdf8',
    inputColor: '#fffdf8',
    textColorBase: '#1b1915',
    textColor1: '#1b1915',
    textColor2: '#5b554b',
    textColor3: '#81796d',
    borderColor: '#dcd4c7',
    dividerColor: '#dcd4c7',
    actionColor: '#ede7db',
    hoverColor: '#f5f1e8',
    successColor: '#2f6b4d',
    warningColor: '#9a611d',
    errorColor: '#b44532',
    infoColor: '#a34b2a',
    borderRadius: '6px',
    borderRadiusSmall: '4px',
    fontFamily: 'ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Noto Sans SC", sans-serif',
    fontFamilyMono: '"SFMono-Regular", Consolas, "Liberation Mono", "Noto Sans Mono CJK SC", monospace',
    fontWeightStrong: '600',
  },
  Button: {
    textColorPrimary: '#fffdf8',
    colorPrimary: '#1b1915',
    colorHoverPrimary: '#413b33',
    colorPressedPrimary: '#1b1915',
    borderPrimary: '1px solid #1b1915',
    borderRadius: '6px',
    borderRadiusSmall: '4px',
    fontWeight: '600',
    fontSize: '14px',
    fontSizeSmall: '13px',
    height: '40px',
    heightSmall: '32px',
  },
  Card: {
    color: '#fffdf8',
    borderColor: '#dcd4c7',
    borderRadius: '8px',
    paddingMedium: '24px',
    paddingSmall: '16px',
    paddingHuge: '32px',
    titleTextColor: '#1b1915',
    titleFontWeight: '600',
  },
  Input: {
    color: '#fffdf8',
    borderColor: '#bcb1a1',
    borderHoverColor: '#6f665a',
    borderFocusColor: '#a34b2a',
    borderRadius: '4px',
    height: '40px',
    textColor: '#1b1915',
    placeholderColor: '#81796d',
    fontSize: '14px',
  },
  Tag: {
    borderRadius: '999px',
    fontSize: '12px',
    fontWeight: '500',
  },
  Alert: { borderRadius: '6px' },
  List: { color: '#fffdf8', borderColor: '#dcd4c7', borderRadius: '8px' },
  Collapse: { titleFontWeight: '600', titleTextColor: '#1b1915', dividerColor: '#dcd4c7', borderRadius: '6px', borderColor: '#dcd4c7' },
  Descriptions: { thColor: '#f5f1e8', tdColor: '#fffdf8', thTextColor: '#81796d', tdTextColor: '#1b1915', borderColor: '#dcd4c7', borderRadius: '6px', thFontWeight: '500', thFontSize: '12px', tdFontSize: '14px' },
  Result: { titleTextColor: '#1b1915', textColor: '#5b554b', iconColorSuccess: '#2f6b4d', iconColorInfo: '#a34b2a' },
  Dialog: { color: '#fffdf8', borderRadius: '8px', titleTextColor: '#1b1915', textColor: '#5b554b' },
  Modal: { color: '#fffdf8', borderRadius: '8px' },
}

export const warmDarkThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#e08b67',
    primaryColorHover: '#e9a081',
    primaryColorPressed: '#c66f4d',
    primaryColorSuppl: '#e08b67',
    bodyColor: '#15130f',
    cardColor: '#1d1a16',
    modalColor: '#1d1a16',
    popoverColor: '#28241e',
    tableColor: '#1d1a16',
    inputColor: '#1d1a16',
    textColorBase: '#f3eee5',
    textColor1: '#f3eee5',
    textColor2: '#c2b9ab',
    textColor3: '#958b7c',
    borderColor: '#383229',
    dividerColor: '#383229',
    actionColor: '#28241e',
    hoverColor: '#28241e',
    successColor: '#8cb999',
    warningColor: '#e2b567',
    errorColor: '#e79482',
    infoColor: '#e08b67',
    borderRadius: '6px',
    borderRadiusSmall: '4px',
    fontFamily: 'ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Noto Sans SC", sans-serif',
    fontFamilyMono: '"SFMono-Regular", Consolas, "Liberation Mono", "Noto Sans Mono CJK SC", monospace',
    fontWeightStrong: '600',
  },
  Button: { textColorPrimary: '#1d1a16', colorPrimary: '#f3eee5', colorHoverPrimary: '#ffffff', colorPressedPrimary: '#e3ddd3', borderPrimary: '1px solid #f3eee5', borderRadius: '6px', borderRadiusSmall: '4px', fontWeight: '600', fontSize: '14px', fontSizeSmall: '13px', height: '40px', heightSmall: '32px' },
  Card: { color: '#1d1a16', borderColor: '#383229', borderRadius: '8px', titleTextColor: '#f3eee5', titleFontWeight: '600' },
  Input: { color: '#1d1a16', borderColor: '#5a5145', borderHoverColor: '#958b7c', borderFocusColor: '#e08b67', borderRadius: '4px', height: '40px', textColor: '#f3eee5', placeholderColor: '#958b7c', fontSize: '14px' },
  Tag: { borderRadius: '999px', fontSize: '12px', fontWeight: '500' },
  Alert: { borderRadius: '6px' },
  List: { color: '#1d1a16', borderColor: '#383229', borderRadius: '8px' },
  Collapse: { titleFontWeight: '600', titleTextColor: '#f3eee5', dividerColor: '#383229', borderRadius: '6px', borderColor: '#383229' },
  Descriptions: { thColor: '#28241e', tdColor: '#1d1a16', thTextColor: '#958b7c', tdTextColor: '#f3eee5', borderColor: '#383229', borderRadius: '6px', thFontWeight: '500', thFontSize: '12px', tdFontSize: '14px' },
  Result: { titleTextColor: '#f3eee5', textColor: '#c2b9ab', iconColorSuccess: '#8cb999', iconColorInfo: '#e08b67' },
  Dialog: { color: '#1d1a16', borderRadius: '8px', titleTextColor: '#f3eee5', textColor: '#c2b9ab' },
  Modal: { color: '#1d1a16', borderRadius: '8px' },
}
