import type { GlobalThemeOverrides } from 'naive-ui'

/* Naive UI mirrors the CSS tokens in styles.css. The default overrides follow
   vercel.md, the warm overrides follow Claude.md; each theme has a light and a
   dark variant so the two stay in step. */

const fontSans =
  '"MiSans", -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif'
const fontMono =
  '"SFMono-Regular", Consolas, "Liberation Mono", "Noto Sans Mono CJK SC", monospace'

// vercel.md — light
export const themeOverrides: GlobalThemeOverrides = {
  common: {
    /* vercel.md: ink is the primary. Blue stays reserved for inline links, so
       switches, radios and progress bars render monochrome. */
    primaryColor: '#171717',
    primaryColorHover: '#383838',
    primaryColorPressed: '#0a0a0a',
    primaryColorSuppl: '#171717',
    bodyColor: '#fafafa',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    tableColor: '#ffffff',
    inputColor: '#ffffff',
    textColorBase: '#171717',
    textColor1: '#171717',
    textColor2: '#4d4d4d',
    textColor3: '#6b6b6b',
    borderColor: '#ebebeb',
    dividerColor: '#ebebeb',
    actionColor: '#f5f5f5',
    hoverColor: '#f5f5f5',
    successColor: '#0e8a72',
    warningColor: '#f5a623',
    errorColor: '#ee0000',
    infoColor: '#0070f3',
    borderRadius: '6px',
    borderRadiusSmall: '4px',
    fontFamily: fontSans,
    fontFamilyMono: fontMono,
    fontWeightStrong: '600',
  },
  Button: {
    textColorPrimary: '#ffffff',
    colorPrimary: '#171717',
    colorHoverPrimary: '#383838',
    colorPressedPrimary: '#0a0a0a',
    borderPrimary: '1px solid #171717',
    borderRadius: '6px',
    borderRadiusSmall: '4px',
    fontWeight: '500',
    fontSize: '13px',
    height: '34px',
    heightSmall: '30px',
    paddingMedium: '0 16px',
  },
  Card: {
    color: '#ffffff',
    borderColor: '#ebebeb',
    borderRadius: '8px',
    paddingMedium: '24px',
    paddingSmall: '20px',
    titleTextColor: '#171717',
    titleFontWeight: '600',
  },
  Input: {
    color: '#ffffff',
    borderColor: '#ebebeb',
    borderHoverColor: '#a1a1a1',
    borderFocusColor: '#171717',
    borderRadius: '6px',
    height: '36px',
    textColor: '#171717',
    placeholderColor: '#6b6b6b',
    fontSize: '13px',
  },
  Select: {
    peers: {
      InternalSelectMenu: { color: '#ffffff' },
    },
  },
  Tag: {
    borderRadius: '999px',
    fontSize: '11px',
    fontWeight: '600',
  },
  Alert: { borderRadius: '6px' },
  List: { color: '#ffffff', borderColor: '#ebebeb', borderRadius: '8px' },
  Collapse: { titleFontWeight: '600', titleTextColor: '#171717', dividerColor: '#ebebeb', borderRadius: '6px', borderColor: '#ebebeb' },
  Descriptions: { thColor: '#fafafa', tdColor: '#ffffff', thTextColor: '#888888', tdTextColor: '#171717', borderColor: '#ebebeb', borderRadius: '6px', thFontWeight: '500', thFontSize: '12px', tdFontSize: '13px' },
  Result: { titleTextColor: '#171717', textColor: '#4d4d4d', iconColorSuccess: '#0e8a72', iconColorInfo: '#0070f3' },
  Dialog: { color: '#ffffff', borderRadius: '8px', titleTextColor: '#171717', textColor: '#4d4d4d' },
  Modal: { color: '#ffffff', borderRadius: '8px' },
}

// vercel.md — dark
export const darkThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#ededed',
    primaryColorHover: '#ffffff',
    primaryColorPressed: '#cccccc',
    primaryColorSuppl: '#ededed',
    bodyColor: '#000000',
    cardColor: '#111111',
    modalColor: '#111111',
    popoverColor: '#1a1a1a',
    tableColor: '#111111',
    inputColor: '#111111',
    textColorBase: '#ededed',
    textColor1: '#ededed',
    textColor2: '#a1a1a1',
    textColor3: '#9a9a9a',
    borderColor: '#2a2a2a',
    dividerColor: '#2a2a2a',
    actionColor: '#1a1a1a',
    hoverColor: '#1a1a1a',
    successColor: '#50e3c2',
    warningColor: '#f5a623',
    errorColor: '#ff6369',
    infoColor: '#3291ff',
    borderRadius: '6px',
    borderRadiusSmall: '4px',
    fontFamily: fontSans,
    fontFamilyMono: fontMono,
    fontWeightStrong: '600',
  },
  Button: { textColorPrimary: '#0a0a0a', colorPrimary: '#ededed', colorHoverPrimary: '#ffffff', colorPressedPrimary: '#cccccc', borderPrimary: '1px solid #ededed', borderRadius: '6px', borderRadiusSmall: '4px', fontWeight: '500', fontSize: '13px', height: '34px', heightSmall: '30px', paddingMedium: '0 16px' },
  Card: { color: '#111111', borderColor: '#2a2a2a', borderRadius: '8px', paddingMedium: '24px', paddingSmall: '20px', titleTextColor: '#ededed', titleFontWeight: '600' },
  Input: { color: '#111111', borderColor: '#2a2a2a', borderHoverColor: '#444444', borderFocusColor: '#ededed', borderRadius: '6px', height: '36px', textColor: '#ededed', placeholderColor: '#9a9a9a', fontSize: '13px' },
  Tag: { borderRadius: '999px', fontSize: '11px', fontWeight: '600' },
  Alert: { borderRadius: '6px' },
  List: { color: '#111111', borderColor: '#2a2a2a', borderRadius: '8px' },
  Collapse: { titleFontWeight: '600', titleTextColor: '#ededed', dividerColor: '#2a2a2a', borderRadius: '6px', borderColor: '#2a2a2a' },
  Descriptions: { thColor: '#1a1a1a', tdColor: '#111111', thTextColor: '#a1a1a1', tdTextColor: '#ededed', borderColor: '#2a2a2a', borderRadius: '6px', thFontWeight: '500', thFontSize: '12px', tdFontSize: '13px' },
  Result: { titleTextColor: '#ededed', textColor: '#a1a1a1', iconColorSuccess: '#50e3c2', iconColorInfo: '#3291ff' },
  Dialog: { color: '#111111', borderRadius: '8px', titleTextColor: '#ededed', textColor: '#a1a1a1' },
  Modal: { color: '#111111', borderRadius: '8px' },
}

// Claude.md — light
export const warmThemeOverrides: GlobalThemeOverrides = {
  ...themeOverrides,
  common: {
    ...themeOverrides.common,
    primaryColor: '#cc785c',
    primaryColorHover: '#a9583e',
    primaryColorPressed: '#8f4a34',
    primaryColorSuppl: '#cc785c',
    bodyColor: '#f5f0e8',
    cardColor: '#faf9f5',
    modalColor: '#faf9f5',
    popoverColor: '#faf9f5',
    tableColor: '#faf9f5',
    inputColor: '#faf9f5',
    textColorBase: '#141413',
    textColor1: '#141413',
    textColor2: '#3d3d3a',
    textColor3: '#5f5d57',
    borderColor: '#e6dfd8',
    dividerColor: '#e6dfd8',
    actionColor: '#efe9de',
    hoverColor: '#f5f0e8',
    successColor: '#5db872',
    warningColor: '#d4a017',
    errorColor: '#c64545',
    infoColor: '#cc785c',
  },
  Button: {
    ...themeOverrides.Button,
    textColorPrimary: '#ffffff',
    colorPrimary: '#cc785c',
    colorHoverPrimary: '#a9583e',
    colorPressedPrimary: '#8f4a34',
    borderPrimary: '1px solid #cc785c',
  },
  Card: { ...themeOverrides.Card, color: '#faf9f5', borderColor: '#e6dfd8', titleTextColor: '#141413' },
  Input: { ...themeOverrides.Input, color: '#faf9f5', borderColor: '#e6dfd8', borderHoverColor: '#c9c0b2', borderFocusColor: '#cc785c', textColor: '#141413', placeholderColor: '#5f5d57' },
  Select: { peers: { InternalSelectMenu: { color: '#faf9f5' } } },
  List: { ...themeOverrides.List, color: '#faf9f5', borderColor: '#e6dfd8' },
  Collapse: { ...themeOverrides.Collapse, titleTextColor: '#141413', dividerColor: '#e6dfd8', borderColor: '#e6dfd8' },
  Descriptions: { ...themeOverrides.Descriptions, thColor: '#f5f0e8', tdColor: '#faf9f5', thTextColor: '#6c6a64', tdTextColor: '#141413', borderColor: '#e6dfd8' },
  Result: { ...themeOverrides.Result, titleTextColor: '#141413', textColor: '#3d3d3a', iconColorSuccess: '#5db872', iconColorInfo: '#cc785c' },
  Dialog: { ...themeOverrides.Dialog, color: '#faf9f5', titleTextColor: '#141413', textColor: '#3d3d3a' },
  Modal: { ...themeOverrides.Modal, color: '#faf9f5' },
}

// Claude.md — dark
export const warmDarkThemeOverrides: GlobalThemeOverrides = {
  ...darkThemeOverrides,
  common: {
    ...darkThemeOverrides.common,
    primaryColor: '#e08b67',
    primaryColorHover: '#eba98b',
    primaryColorPressed: '#cc785c',
    primaryColorSuppl: '#e08b67',
    bodyColor: '#181715',
    cardColor: '#1f1e1b',
    modalColor: '#1f1e1b',
    popoverColor: '#252320',
    tableColor: '#1f1e1b',
    inputColor: '#1f1e1b',
    textColorBase: '#faf9f5',
    textColor1: '#faf9f5',
    textColor2: '#a09d96',
    textColor3: '#a8a49c',
    borderColor: '#33312c',
    dividerColor: '#33312c',
    actionColor: '#252320',
    hoverColor: '#252320',
    successColor: '#5db872',
    warningColor: '#e8a55a',
    errorColor: '#e07a7a',
    infoColor: '#e08b67',
  },
  Button: {
    ...darkThemeOverrides.Button,
    textColorPrimary: '#ffffff',
    colorPrimary: '#cc785c',
    colorHoverPrimary: '#a9583e',
    colorPressedPrimary: '#b4674e',
    borderPrimary: '1px solid #cc785c',
  },
  Card: { ...darkThemeOverrides.Card, color: '#1f1e1b', borderColor: '#33312c', titleTextColor: '#faf9f5' },
  Input: { ...darkThemeOverrides.Input, color: '#1f1e1b', borderColor: '#33312c', borderHoverColor: '#4a4741', borderFocusColor: '#e08b67', textColor: '#faf9f5', placeholderColor: '#a8a49c' },
  Select: { peers: { InternalSelectMenu: { color: '#1f1e1b' } } },
  List: { ...darkThemeOverrides.List, color: '#1f1e1b', borderColor: '#33312c' },
  Collapse: { ...darkThemeOverrides.Collapse, titleTextColor: '#faf9f5', dividerColor: '#33312c', borderColor: '#33312c' },
  Descriptions: { ...darkThemeOverrides.Descriptions, thColor: '#252320', tdColor: '#1f1e1b', thTextColor: '#8e8b82', tdTextColor: '#faf9f5', borderColor: '#33312c' },
  Result: { ...darkThemeOverrides.Result, titleTextColor: '#faf9f5', textColor: '#a09d96', iconColorSuccess: '#5db872', iconColorInfo: '#e08b67' },
  Dialog: { ...darkThemeOverrides.Dialog, color: '#1f1e1b', titleTextColor: '#faf9f5', textColor: '#a09d96' },
  Modal: { ...darkThemeOverrides.Modal, color: '#1f1e1b' },
}
