import type { GlobalThemeOverrides } from 'naive-ui'

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#2563eb',
    primaryColorHover: '#1d4ed8',
    primaryColorPressed: '#1e40af',
    primaryColorSuppl: '#2563eb',
    bodyColor: '#f8fafc',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    tableColor: '#ffffff',
    inputColor: '#ffffff',
    textColorBase: '#0f172a',
    textColor1: '#0f172a',
    textColor2: '#475569',
    textColor3: '#64748b',
    borderColor: '#e2e8f0',
    dividerColor: '#e2e8f0',
    actionColor: '#f1f5f9',
    hoverColor: '#f1f5f9',
    successColor: '#10b981',
    warningColor: '#f59e0b',
    errorColor: '#ef4444',
    infoColor: '#2563eb',
    borderRadius: '6px',
    borderRadiusSmall: '4px',
    fontFamily: '"MiSans", -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
    fontFamilyMono: '"SFMono-Regular", Consolas, "Liberation Mono", "Noto Sans Mono CJK SC", monospace',
    fontWeightStrong: '600',
  },
  Button: {
    textColorPrimary: '#ffffff',
    colorPrimary: '#0f172a',
    colorHoverPrimary: '#283244',
    colorPressedPrimary: '#0b1220',
    borderPrimary: '1px solid #0f172a',
    borderRadius: '6px',
    borderRadiusSmall: '4px',
    fontWeight: '500',
    fontSize: '13px',
    height: '32px',
    heightSmall: '28px',
    paddingMedium: '0 14px',
  },
  Card: {
    color: '#ffffff',
    borderColor: '#e2e8f0',
    borderRadius: '8px',
    paddingMedium: '20px',
    paddingSmall: '16px',
    titleTextColor: '#0f172a',
    titleFontWeight: '600',
  },
  Input: {
    color: '#ffffff',
    borderColor: '#e2e8f0',
    borderHoverColor: '#cbd5e1',
    borderFocusColor: '#2563eb',
    borderRadius: '6px',
    height: '32px',
    textColor: '#0f172a',
    placeholderColor: '#94a3b8',
    fontSize: '13px',
  },
  Select: {
    peers: {
      InternalSelectMenu: { color: '#ffffff' },
    },
  },
  Tag: {
    borderRadius: '999px',
    fontSize: '11px',
    fontWeight: '600',
  },
  Alert: { borderRadius: '6px' },
  List: { color: '#ffffff', borderColor: '#e2e8f0', borderRadius: '8px' },
  Collapse: { titleFontWeight: '600', titleTextColor: '#0f172a', dividerColor: '#e2e8f0', borderRadius: '6px', borderColor: '#e2e8f0' },
  Descriptions: { thColor: '#f8fafc', tdColor: '#ffffff', thTextColor: '#64748b', tdTextColor: '#0f172a', borderColor: '#e2e8f0', borderRadius: '6px', thFontWeight: '500', thFontSize: '12px', tdFontSize: '13px' },
  Result: { titleTextColor: '#0f172a', textColor: '#475569', iconColorSuccess: '#10b981', iconColorInfo: '#2563eb' },
  Dialog: { color: '#ffffff', borderRadius: '8px', titleTextColor: '#0f172a', textColor: '#475569' },
  Modal: { color: '#ffffff', borderRadius: '8px' },
}

export const darkThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#60a5fa',
    primaryColorHover: '#93c5fd',
    primaryColorPressed: '#3b82f6',
    primaryColorSuppl: '#60a5fa',
    bodyColor: '#0f172a',
    cardColor: '#1e293b',
    modalColor: '#1e293b',
    popoverColor: '#1e293b',
    tableColor: '#1e293b',
    inputColor: '#1e293b',
    textColorBase: '#f8fafc',
    textColor1: '#f8fafc',
    textColor2: '#94a3b8',
    textColor3: '#64748b',
    borderColor: '#334155',
    dividerColor: '#334155',
    actionColor: '#1e293b',
    hoverColor: '#334155',
    successColor: '#34d399',
    warningColor: '#fbbf24',
    errorColor: '#f87171',
    infoColor: '#60a5fa',
    borderRadius: '6px',
    borderRadiusSmall: '4px',
    fontFamily: '"MiSans", -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
    fontFamilyMono: '"SFMono-Regular", Consolas, "Liberation Mono", "Noto Sans Mono CJK SC", monospace',
    fontWeightStrong: '600',
  },
  Button: { textColorPrimary: '#0f172a', colorPrimary: '#f8fafc', colorHoverPrimary: '#ffffff', colorPressedPrimary: '#cbd5e1', borderPrimary: '1px solid #f8fafc', borderRadius: '6px', borderRadiusSmall: '4px', fontWeight: '500', fontSize: '13px', height: '32px', heightSmall: '28px' },
  Card: { color: '#1e293b', borderColor: '#334155', borderRadius: '8px', titleTextColor: '#f8fafc', titleFontWeight: '600' },
  Input: { color: '#1e293b', borderColor: '#334155', borderHoverColor: '#475569', borderFocusColor: '#60a5fa', borderRadius: '6px', height: '32px', textColor: '#f8fafc', placeholderColor: '#64748b', fontSize: '13px' },
  Tag: { borderRadius: '999px', fontSize: '11px', fontWeight: '600' },
  Alert: { borderRadius: '6px' },
  List: { color: '#1e293b', borderColor: '#334155', borderRadius: '8px' },
  Collapse: { titleFontWeight: '600', titleTextColor: '#f8fafc', dividerColor: '#334155', borderRadius: '6px', borderColor: '#334155' },
  Descriptions: { thColor: '#1e293b', tdColor: '#1e293b', thTextColor: '#94a3b8', tdTextColor: '#f8fafc', borderColor: '#334155', borderRadius: '6px', thFontWeight: '500', thFontSize: '12px', tdFontSize: '13px' },
  Result: { titleTextColor: '#f8fafc', textColor: '#94a3b8', iconColorSuccess: '#34d399', iconColorInfo: '#60a5fa' },
  Dialog: { color: '#1e293b', borderRadius: '8px', titleTextColor: '#f8fafc', textColor: '#94a3b8' },
  Modal: { color: '#1e293b', borderRadius: '8px' },
}

export const warmThemeOverrides: GlobalThemeOverrides = {
  ...themeOverrides,
  common: {
    ...themeOverrides.common,
    primaryColor: '#a34b2a',
    primaryColorHover: '#82391f',
    primaryColorPressed: '#6a2d19',
    primaryColorSuppl: '#a34b2a',
    bodyColor: '#f5f1e8',
    cardColor: '#fffdf8',
    modalColor: '#fffdf8',
    popoverColor: '#fffdf8',
    tableColor: '#fffdf8',
    inputColor: '#fffdf8',
    textColorBase: '#1b1915',
    textColor1: '#1b1915',
    textColor2: '#5b554b',
    textColor3: '#81796d',
    borderColor: '#dcd4c7',
    dividerColor: '#dcd4c7',
    actionColor: '#ede7db',
    hoverColor: '#f5f1e8',
    successColor: '#2f6b4d',
    warningColor: '#9a611d',
    errorColor: '#b44532',
    infoColor: '#a34b2a',
  },
  Button: {
    ...themeOverrides.Button,
    textColorPrimary: '#fffdf8',
    colorPrimary: '#1b1915',
    colorHoverPrimary: '#413b33',
    colorPressedPrimary: '#1b1915',
    borderPrimary: '1px solid #1b1915',
  },
  Card: { ...themeOverrides.Card, color: '#fffdf8', borderColor: '#dcd4c7', titleTextColor: '#1b1915' },
  Input: { ...themeOverrides.Input, color: '#fffdf8', borderColor: '#bcb1a1', borderHoverColor: '#6f665a', borderFocusColor: '#a34b2a', textColor: '#1b1915', placeholderColor: '#81796d' },
  Select: { peers: { InternalSelectMenu: { color: '#fffdf8' } } },
  List: { ...themeOverrides.List, color: '#fffdf8', borderColor: '#dcd4c7' },
  Collapse: { ...themeOverrides.Collapse, titleTextColor: '#1b1915', dividerColor: '#dcd4c7', borderColor: '#dcd4c7' },
  Descriptions: { ...themeOverrides.Descriptions, thColor: '#f5f1e8', tdColor: '#fffdf8', thTextColor: '#81796d', tdTextColor: '#1b1915', borderColor: '#dcd4c7' },
  Result: { ...themeOverrides.Result, titleTextColor: '#1b1915', textColor: '#5b554b', iconColorSuccess: '#2f6b4d', iconColorInfo: '#a34b2a' },
  Dialog: { ...themeOverrides.Dialog, color: '#fffdf8', titleTextColor: '#1b1915', textColor: '#5b554b' },
  Modal: { ...themeOverrides.Modal, color: '#fffdf8' },
}

export const warmDarkThemeOverrides: GlobalThemeOverrides = {
  ...darkThemeOverrides,
  common: {
    ...darkThemeOverrides.common,
    primaryColor: '#e08b67',
    primaryColorHover: '#e9a081',
    primaryColorPressed: '#c66f4d',
    primaryColorSuppl: '#e08b67',
    bodyColor: '#15130f',
    cardColor: '#1d1a16',
    modalColor: '#1d1a16',
    popoverColor: '#28241e',
    tableColor: '#1d1a16',
    inputColor: '#1d1a16',
    textColorBase: '#f3eee5',
    textColor1: '#f3eee5',
    textColor2: '#c2b9ab',
    textColor3: '#958b7c',
    borderColor: '#383229',
    dividerColor: '#383229',
    actionColor: '#28241e',
    hoverColor: '#28241e',
    successColor: '#8cb999',
    warningColor: '#e2b567',
    errorColor: '#e79482',
    infoColor: '#e08b67',
  },
  Button: {
    ...darkThemeOverrides.Button,
    textColorPrimary: '#1d1a16',
    colorPrimary: '#f3eee5',
    colorHoverPrimary: '#ffffff',
    colorPressedPrimary: '#e3ddd3',
    borderPrimary: '1px solid #f3eee5',
  },
  Card: { ...darkThemeOverrides.Card, color: '#1d1a16', borderColor: '#383229', titleTextColor: '#f3eee5' },
  Input: { ...darkThemeOverrides.Input, color: '#1d1a16', borderColor: '#5a5145', borderHoverColor: '#958b7c', borderFocusColor: '#e08b67', textColor: '#f3eee5', placeholderColor: '#958b7c' },
  Select: { peers: { InternalSelectMenu: { color: '#1d1a16' } } },
  List: { ...darkThemeOverrides.List, color: '#1d1a16', borderColor: '#383229' },
  Collapse: { ...darkThemeOverrides.Collapse, titleTextColor: '#f3eee5', dividerColor: '#383229', borderColor: '#383229' },
  Descriptions: { ...darkThemeOverrides.Descriptions, thColor: '#28241e', tdColor: '#1d1a16', thTextColor: '#958b7c', tdTextColor: '#f3eee5', borderColor: '#383229' },
  Result: { ...darkThemeOverrides.Result, titleTextColor: '#f3eee5', textColor: '#c2b9ab', iconColorSuccess: '#8cb999', iconColorInfo: '#e08b67' },
  Dialog: { ...darkThemeOverrides.Dialog, color: '#1d1a16', titleTextColor: '#f3eee5', textColor: '#c2b9ab' },
  Modal: { ...darkThemeOverrides.Modal, color: '#1d1a16' },
}
